language: php
php:
    - '5.5'

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - "sh start-server.sh > /dev/null &"

script:
    - bin/behat